return {
  boxes = {
    [1] = {},
    [2] = {},
    [3] = {},
    [4] = {},
    [5] = {},
    [6] = {},
    [7] = {},
    [8] = {},
    [9] = {},
    [10] = {},
    [11] = {},
    [12] = {
      [1] = {
        dvs = {
          [1] = 15,
          [2] = 12,
          [3] = 10,
          [4] = 9,
        },
        exp = 1000,
        hp = 20,
        level = 8,
        maxHp = 20,
        moves = {
          [1] = {
            id = "TACKLE",
            pp = 35,
          },
        },
        nickname = "TWELVE",
        otId = 12345,
        otName = "ASH",
        species = "ODDISH",
        statExp = {
          [1] = 0,
          [2] = 0,
          [3] = 0,
          [4] = 0,
          [5] = 0,
        },
        stats = {
          attack = 12,
          defense = 11,
          hp = 20,
          special = 14,
          speed = 13,
        },
      },
    },
    [13] = {},
    [14] = {},
    [15] = {},
    [16] = {},
    [17] = {},
    [18] = {},
    [19] = {},
    [20] = {},
    [21] = {},
    [22] = {},
    [23] = {},
    [24] = {
      [1] = {
        dvs = {
          [1] = 15,
          [2] = 12,
          [3] = 10,
          [4] = 9,
        },
        exp = 1000,
        hp = 20,
        level = 16,
        maxHp = 20,
        moves = {
          [1] = {
            id = "TACKLE",
            pp = 35,
          },
        },
        nickname = "LAST",
        otId = 12345,
        otName = "ASH",
        species = "ABRA",
        statExp = {
          [1] = 0,
          [2] = 0,
          [3] = 0,
          [4] = 0,
          [5] = 0,
        },
        stats = {
          attack = 12,
          defense = 11,
          hp = 20,
          special = 14,
          speed = 13,
        },
      },
    },
  },
  currentBox = 20,
  inventory = {
    BOULDERBADGE = 1,
    POTION = 3,
  },
  meta = {
    format = 5,
    mods = {
      tm32_double_team = {
        boxCapacity = 20,
        boxCount = 24,
        name = "TM32 Double Team",
        version = "1.3",
      },
    },
    playthroughId = "quiet-forest-dawn",
  },
  party = {
    [1] = {
      dvs = {
        [1] = 15,
        [2] = 12,
        [3] = 10,
        [4] = 9,
      },
      exp = 1000,
      hp = 20,
      level = 25,
      maxHp = 20,
      moves = {
        [1] = {
          id = "TACKLE",
          pp = 35,
        },
      },
      nickname = "SPARKY",
      otId = 12345,
      otName = "ASH",
      species = "PIKACHU",
      statExp = {
        [1] = 0,
        [2] = 0,
        [3] = 0,
        [4] = 0,
        [5] = 0,
      },
      stats = {
        attack = 12,
        defense = 11,
        hp = 20,
        special = 14,
        speed = 13,
      },
    },
  },
  pcItems = {
    POTION = 1,
  },
  playTime = 7265.5,
  player = {
    facing = "down",
    id = 12345,
    map = "PALLET_TOWN",
    name = "ASH",
    rival = "BLUE",
    x = 5,
    y = 6,
  },
  pokedex = {
    owned = {
      PIKACHU = true,
    },
    seen = {
      PIKACHU = true,
    },
  },
  version = "red",
}
