// GENERATED FILE - do not edit by hand.
// Source: pret/pokered @ a1a22aaf84d1675bcdbaeb194592379d586d838e
//     and pret/pokeyellow @ unknown,
// via tools/generate_gen1_dex.py.
// Species ids are the pokered constant names Gen1Recomp writes into
// save.lua. Height is feet and inches and weight is tenths of a pound,
// which is how the cartridge stores them.
package com.logie.gen1storage.pokemon

internal val GEN1_DEX_TABLE: List<Gen1DexEntry> = listOf(
    Gen1DexEntry(
        "ABRA",
        "PSI",
        2, 11, 430,
        "Using its ability\nto read minds, it\nwill identify\n\nimpending danger\nand TELEPORT to\nsafety",
        "Sleeps 18 hours a\nday. If it senses\ndanger, it will\n\nteleport itself to\nsafety even as it\nsleeps",
    ),
    Gen1DexEntry(
        "AERODACTYL",
        "FOSSIL",
        5, 11, 1300,
        "A ferocious, pre-\nhistoric POKéMON\nthat goes for the\n\nenemy's throat\nwith its serrated\nsaw-like fangs",
        "A savage POKéMON\nthat died out in\nancient times. It\n\nwas resurrected\nusing DNA taken\nfrom amber",
    ),
    Gen1DexEntry(
        "ALAKAZAM",
        "PSI",
        4, 11, 1060,
        "Its brain can out-\nperform a super-\ncomputer.\n\nIts intelligence\nquotient is said\nto be 5,000",
        "A POKéMON that can\nmemorize anything.\nIt never forgets\n\nwhat it learns--\nthat's why this\nPOKéMON is smart",
    ),
    Gen1DexEntry(
        "ARBOK",
        "COBRA",
        11, 6, 1430,
        "It is rumored that\nthe ferocious\nwarning markings\n\non its belly\ndiffer from area\nto area",
        "The frightening\npatterns on its\nbelly have been\n\nstudied. Six\nvariations have\nbeen confirmed",
    ),
    Gen1DexEntry(
        "ARCANINE",
        "LEGENDARY",
        6, 3, 3420,
        "A POKéMON that\nhas been admired\nsince the past\n\nfor its beauty.\nIt runs agilely\nas if on wings",
        "A legendary POKé-\nMON in China.\nMany people are\n\ncharmed by its\ngrace and beauty\nwhile running",
    ),
    Gen1DexEntry(
        "ARTICUNO",
        "FREEZE",
        5, 7, 1220,
        "A legendary bird\nPOKéMON that is\nsaid to appear to\n\ndoomed people who\nare lost in icy\nmountains",
        "A legendary bird\nPOKéMON. It\nfreezes water\n\nthat is contained\nin winter air and\nmakes it snow",
    ),
    Gen1DexEntry(
        "BEEDRILL",
        "POISON BEE",
        3, 3, 650,
        "Flies at high\nspeed and attacks\nusing its large\n\nvenomous stingers\non its forelegs\nand tail",
        "It has 3 poisonous\nstingers on its\nforelegs and its\n\ntail. They are\nused to jab its\nenemy repeatedly",
    ),
    Gen1DexEntry(
        "BELLSPROUT",
        "FLOWER",
        2, 4, 90,
        "A carnivorous\nPOKéMON that traps\nand eats bugs.\n\nIt uses its root\nfeet to soak up\nneeded moisture",
        "Prefers hot and\nhumid places.\nIt ensnares tiny\n\ninsects with its\nvines and devours\nthem",
    ),
    Gen1DexEntry(
        "BLASTOISE",
        "SHELLFISH",
        5, 3, 1890,
        "A brutal POKéMON\nwith pressurized\nwater jets on its\n\nshell. They are\nused for high\nspeed tackles",
        "Once it takes aim\nat its enemy, it\nblasts out water\n\nwith even more\nforce than a fire\nhose",
    ),
    Gen1DexEntry(
        "BULBASAUR",
        "SEED",
        2, 4, 150,
        "A strange seed was\nplanted on its\nback at birth.\n\nThe plant sprouts\nand grows with\nthis POKéMON",
        "It can go for days\nwithout eating a\nsingle morsel.\n\nIn the bulb on\nits back, it\nstores energy",
    ),
    Gen1DexEntry(
        "BUTTERFREE",
        "BUTTERFLY",
        3, 7, 710,
        "In battle, it\nflaps its wings\nat high speed to\n\nrelease highly\ntoxic dust into\nthe air",
        "Its wings, covered\nwith poisonous\npowders, repel\n\nwater. This\nallows it to fly\nin the rain",
    ),
    Gen1DexEntry(
        "CATERPIE",
        "WORM",
        1, 0, 60,
        "Its short feet\nare tipped with\nsuction pads that\n\nenable it to\ntirelessly climb\nslopes and walls",
        "If you touch the\nfeeler on top of\nits head, it will\n\nrelease a horrible\nstink to protect\nitself",
    ),
    Gen1DexEntry(
        "CHANSEY",
        "EGG",
        3, 7, 760,
        "A rare and elusive\nPOKéMON that is\nsaid to bring\n\nhappiness to those\nwho manage to get\nit",
        "A gentle and kind-\nhearted POKéMON\nthat shares its\n\nnutritious eggs\nif it sees an\ninjured POKéMON",
    ),
    Gen1DexEntry(
        "CHARIZARD",
        "FLAME",
        5, 7, 2000,
        "Spits fire that\nis hot enough to\nmelt boulders.\n\nKnown to cause\nforest fires\nunintentionally",
        "When expelling a\nblast of super\nhot fire, the red\n\nflame at the tip\nof its tail burns\nmore intensely",
    ),
    Gen1DexEntry(
        "CHARMANDER",
        "LIZARD",
        2, 0, 190,
        "Obviously prefers\nhot places. When\nit rains, steam\n\nis said to spout\nfrom the tip of\nits tail",
        "The flame at the\ntip of its tail\nmakes a sound as\n\nit burns. You can\nonly hear it in\nquiet places",
    ),
    Gen1DexEntry(
        "CHARMELEON",
        "FLAME",
        3, 7, 420,
        "When it swings\nits burning tail,\nit elevates the\n\ntemperature to\nunbearably high\nlevels",
        "Tough fights could\nexcite this\nPOKéMON. When\n\nexcited, it may\nblow out bluish-\nwhite flames",
    ),
    Gen1DexEntry(
        "CLEFABLE",
        "FAIRY",
        4, 3, 880,
        "A timid fairy\nPOKéMON that is\nrarely seen. It\n\nwill run and hide\nthe moment it\nsenses people",
        "They appear to be\nvery protective of\ntheir own world.\n\nIt is a kind of\nfairy, rarely seen\nby people",
    ),
    Gen1DexEntry(
        "CLEFAIRY",
        "FAIRY",
        2, 0, 170,
        "Its magical and\ncute appeal has\nmany admirers.\n\nIt is rare and\nfound only in\ncertain areas",
        "Adored for their\ncute looks and\nplayfulness. They\n\nare thought to be\nrare, as they do\nnot appear often",
    ),
    Gen1DexEntry(
        "CLOYSTER",
        "BIVALVE",
        4, 11, 2920,
        "When attacked, it\nlaunches its\nhorns in quick\n\nvolleys. Its\ninnards have\nnever been seen",
        "For protection, it\nuses its harder-\nthan-diamonds\n\nshell. It also\nshoots spikes from\nthe shell",
    ),
    Gen1DexEntry(
        "CUBONE",
        "LONELY",
        1, 4, 140,
        "Because it never\nremoves its skull\nhelmet, no one\n\nhas ever seen\nthis POKéMON's\nreal face",
        "Wears the skull\nof its deceased\nmother. Its cries\n\necho inside the\nskull and come out\nas a sad melody",
    ),
    Gen1DexEntry(
        "DEWGONG",
        "SEA LION",
        5, 7, 2650,
        "Stores thermal\nenergy in its\nbody. Swims at a\n\nsteady 8 knots\neven in intensely\ncold waters",
        "Its entire body is\na snowy-white.\nUnharmed by even\n\nintense cold, it\nswims powerfully\nin icy waters",
    ),
    Gen1DexEntry(
        "DIGLETT",
        "MOLE",
        0, 8, 20,
        "Lives about one\nyard underground\nwhere it feeds on\n\nplant roots. It\nsometimes appears\nabove ground",
        "It prefers dark\nplaces. It spends\nmost of its time\n\nunderground,\nthough it may pop\nup in caves",
    ),
    Gen1DexEntry(
        "DITTO",
        "TRANSFORM",
        1, 0, 90,
        "Capable of copying\nan enemy's genetic\ncode to instantly\n\ntransform itself\ninto a duplicate\nof the enemy",
        "When it spots an\nenemy, its body\ntransfigures into\n\nan almost perfect\ncopy of its oppo-\nnent",
    ),
    Gen1DexEntry(
        "DODRIO",
        "TRIPLEBIRD",
        5, 11, 1880,
        "Uses its three\nbrains to execute\ncomplex plans.\n\nWhile two heads\nsleep, one head\nstays awake",
        "One of DODUO's 2\nheads splits to\nform a unique\n\nspecies. It runs\nclose to 40 MPH\nin prairies",
    ),
    Gen1DexEntry(
        "DODUO",
        "TWIN BIRD",
        4, 7, 860,
        "A bird that makes\nup for its poor\nflying with its\n\nfast foot speed.\nLeaves giant\nfootprints",
        "Its short wings\nmake flying dif-\nficult. Instead,\n\nthis POKéMON runs\nat high speed on\ndeveloped legs",
    ),
    Gen1DexEntry(
        "DRAGONAIR",
        "DRAGON",
        13, 1, 360,
        "A mystical POKéMON\nthat exudes a\ngentle aura.\n\nHas the ability\nto change climate\nconditions",
        "According to a\nwitness, its body\nwas surrounded by\n\na strange aura\nthat gave it a\nmystical look",
    ),
    Gen1DexEntry(
        "DRAGONITE",
        "DRAGON",
        7, 3, 4630,
        "An extremely\nrarely seen\nmarine POKéMON.\n\nIts intelligence\nis said to match\nthat of humans",
        "It is said that\nthis POKéMON lives\nsomewhere in the\n\nsea and that it\nflies. However, it\nis only a rumor",
    ),
    Gen1DexEntry(
        "DRATINI",
        "DRAGON",
        5, 11, 70,
        "Long considered a\nmythical POKéMON\nuntil recently\n\nwhen a small\ncolony was found\nliving underwater",
        "The existence of\nthis mythical\nPOKéMON was only\n\nrecently confirmed\nby a fisherman\nwho caught one",
    ),
    Gen1DexEntry(
        "DROWZEE",
        "HYPNOSIS",
        3, 3, 710,
        "Puts enemies to\nsleep then eats\ntheir dreams.\n\nOccasionally gets\nsick from eating\nbad dreams",
        "If you sleep by\nit all the time,\nit will sometimes\n\nshow you dreams\nit has eaten in\nthe past",
    ),
    Gen1DexEntry(
        "DUGTRIO",
        "MOLE",
        2, 4, 730,
        "A team of DIGLETT\ntriplets.\nIt triggers huge\n\nearthquakes by\nburrowing 60 miles\nunderground",
        "A team of triplets\nthat can burrow\nover 60 MPH.\n\nDue to this, some\npeople think it's\nan earthquake",
    ),
    Gen1DexEntry(
        "EEVEE",
        "EVOLUTION",
        1, 0, 140,
        "Its genetic code\nis irregular.\nIt may mutate if\n\nit is exposed to\nradiation from\nelement STONEs",
        "Its genetic code\nis unstable, so it\ncould evolve in\n\na variety of ways.\nThere are only a\nfew alive",
    ),
    Gen1DexEntry(
        "EKANS",
        "SNAKE",
        6, 7, 150,
        "Moves silently\nand stealthily.\nEats the eggs of\n\nbirds, such as\nPIDGEY and\nSPEAROW, whole",
        "The older it gets,\nthe longer it\ngrows. At night,\n\nit wraps its long\nbody around tree\nbranches to rest",
    ),
    Gen1DexEntry(
        "ELECTABUZZ",
        "ELECTRIC",
        3, 7, 660,
        "Normally found\nnear power plants,\nthey can wander\n\naway and cause\nmajor blackouts\nin cities",
        "If a major power\noutage occurs, it\nis certain that\n\nthis POKéMON has\neaten electricity\nat a power plant",
    ),
    Gen1DexEntry(
        "ELECTRODE",
        "BALL",
        3, 11, 1470,
        "It stores electric\nenergy under very\nhigh pressure.\n\nIt often explodes\nwith little or no\nprovocation",
        "Stores electrical\nenergy inside its\nbody. Even the\n\nslightest shock\ncould trigger a\nhuge explosion",
    ),
    Gen1DexEntry(
        "EXEGGCUTE",
        "EGG",
        1, 4, 60,
        "Often mistaken\nfor eggs.\nWhen disturbed,\n\nthey quickly\ngather and attack\nin swarms",
        "The heads attract\neach other and\nspin around.\n\nThere must be 6\nheads for it to\nmaintain balance",
    ),
    Gen1DexEntry(
        "EXEGGUTOR",
        "COCONUT",
        6, 7, 2650,
        "Legend has it that\non rare occasions,\none of its heads\n\nwill drop off and\ncontinue on as an\nEXEGGCUTE",
        "Its cries are very\nnoisy. This is\nbecause each of\n\nthe 3 heads thinks\nabout whatever it\nlikes",
    ),
    Gen1DexEntry(
        "FARFETCHD",
        "WILD DUCK",
        2, 7, 330,
        "The sprig of\ngreen onions it\nholds is its\n\nweapon. It is\nused much like a\nmetal sword",
        "Lives where reedy\nplants grow. They\nare rarely seen,\n\nso it's thought\ntheir numbers are\ndecreasing",
    ),
    Gen1DexEntry(
        "FEAROW",
        "BEAK",
        3, 11, 840,
        "With its huge and\nmagnificent wings,\nit can keep aloft\n\nwithout ever\nhaving to land\nfor rest",
        "A POKéMON that\ndates back many\nyears. If it\n\nsenses danger, it\nflies high and\naway, instantly",
    ),
    Gen1DexEntry(
        "FLAREON",
        "FLAME",
        2, 11, 550,
        "When storing\nthermal energy in\nits body, its\n\ntemperature could\nsoar to over 1600\ndegrees",
        "It has a flame\nchamber inside its\nbody. It inhales,\n\nthen blows out\nfire that is over\n3,000F degrees",
    ),
    Gen1DexEntry(
        "GASTLY",
        "GAS",
        4, 3, 2,
        "Almost invisible,\nthis gaseous\nPOKéMON cloaks\n\nthe target and\nputs it to sleep\nwithout notice",
        "Said to appear in\ndecrepit, deserted\nbuildings. It has\n\nno real shape as\nit appears to be\nmade of a gas",
    ),
    Gen1DexEntry(
        "GENGAR",
        "SHADOW",
        4, 11, 890,
        "Under a full moon,\nthis POKéMON\nlikes to mimic\n\nthe shadows of\npeople and laugh\nat their fright",
        "A GENGAR is close\nby if you feel a\nsudden chill.\n\nIt may be trying\nto lay a curse\non you",
    ),
    Gen1DexEntry(
        "GEODUDE",
        "ROCK",
        1, 4, 440,
        "Found in fields\nand mountains.\nMistaking them\n\nfor boulders,\npeople often step\nor trip on them",
        "Commonly found\nnear mountain\ntrails, etc.\n\nIf you step on\none by accident,\nit gets angry",
    ),
    Gen1DexEntry(
        "GLOOM",
        "WEED",
        2, 7, 190,
        "The fluid that\noozes from its\nmouth isn't drool.\n\nIt is a nectar\nthat is used to\nattract prey",
        "Smells incredibly\nfoul! However,\naround 1 out of\n\n1,000 people enjoy\nsniffing its nose-\nbending stink",
    ),
    Gen1DexEntry(
        "GOLBAT",
        "BAT",
        5, 3, 1210,
        "Once it strikes,\nit will not stop\ndraining energy\n\nfrom the victim\neven if it gets\ntoo heavy to fly",
        "It attacks in a\nstealthy manner,\nwithout warning.\n\nIts sharp fangs\nare used to bite\nand suck blood",
    ),
    Gen1DexEntry(
        "GOLDEEN",
        "GOLDFISH",
        2, 0, 330,
        "Its tail fin\nbillows like an\nelegant ballroom\n\ndress, giving it\nthe nickname of\nthe Water Queen",
        "When it is time\nfor them to lay\neggs, they can be\n\nseen swimming up\nrivers and falls\nin large groups",
    ),
    Gen1DexEntry(
        "GOLDUCK",
        "DUCK",
        5, 7, 1690,
        "Often seen swim-\nming elegantly by\nlake shores. It\n\nis often mistaken\nfor the Japanese\nmonster, Kappa",
        "Its slim and long\nlimbs end in broad\nflippers. They\n\nare used for swim-\nming gracefully\nin lakes",
    ),
    Gen1DexEntry(
        "GOLEM",
        "MEGATON",
        4, 7, 6620,
        "Its boulder-like\nbody is extremely\nhard. It can\n\neasily withstand\ndynamite blasts\nwithout damage",
        "Once it sheds its\nskin, its body\nturns tender and\n\nwhitish. Its hide\nhardens when it's\nexposed to air",
    ),
    Gen1DexEntry(
        "GRAVELER",
        "ROCK",
        3, 3, 2320,
        "Rolls down slopes\nto move. It rolls\nover any obstacle\n\nwithout slowing\nor changing its\ndirection",
        "Often seen rolling\ndown mountain\ntrails. Obstacles\n\nare just things to\nroll straight\nover, not avoid",
    ),
    Gen1DexEntry(
        "GRIMER",
        "SLUDGE",
        2, 11, 660,
        "Appears in filthy\nareas. Thrives by\nsucking up\n\npolluted sludge\nthat is pumped\nout of factories",
        "Made of hardened\nsludge. It smells\ntoo putrid to\n\ntouch.\nEven weeds won't\ngrow in its path",
    ),
    Gen1DexEntry(
        "GROWLITHE",
        "PUPPY",
        2, 4, 420,
        "Very protective\nof its territory.\nIt will bark and\n\nbite to repel\nintruders from\nits space",
        "A POKéMON with a\nfriendly nature.\nHowever, it will\n\nbark fiercely at\nanything invading\nits territory",
    ),
    Gen1DexEntry(
        "GYARADOS",
        "ATROCIOUS",
        21, 4, 5180,
        "Rarely seen in\nthe wild. Huge\nand vicious, it\n\nis capable of\ndestroying entire\ncities in a rage",
        "Brutally vicious\nand enormously\ndestructive.\n\nKnown for totally\ndestroying cities\nin ancient times",
    ),
    Gen1DexEntry(
        "HAUNTER",
        "GAS",
        5, 3, 2,
        "Because of its\nability to slip\nthrough block\n\nwalls, it is said\nto be from an-\nother dimension",
        "By licking, it\nsaps the victim's\nlife. It causes\n\nshaking that won't\nstop until the\nvictim's demise",
    ),
    Gen1DexEntry(
        "HITMONCHAN",
        "PUNCHING",
        4, 7, 1110,
        "While apparently\ndoing nothing, it\nfires punches in\n\nlightning fast\nvolleys that are\nimpossible to see",
        "Punches in cork-\nscrew fashion. It\ncan punch its way\n\nthrough a concrete\nwall in the same\nway as a drill",
    ),
    Gen1DexEntry(
        "HITMONLEE",
        "KICKING",
        4, 11, 1100,
        "When in a hurry,\nits legs lengthen\nprogressively.\n\nIt runs smoothly\nwith extra long,\nloping strides",
        "When kicking, the\nsole of its foot\nturns as hard as\n\na diamond on im-\npact and destroys\nits enemy",
    ),
    Gen1DexEntry(
        "HORSEA",
        "DRAGON",
        1, 4, 180,
        "Known to shoot\ndown flying bugs\nwith precision\n\nblasts of ink\nfrom the surface\nof the water",
        "If it senses any\ndanger, it will\nvigorously spray\n\nwater or a special\ntype of ink from\nits mouth",
    ),
    Gen1DexEntry(
        "HYPNO",
        "HYPNOSIS",
        5, 3, 1670,
        "When it locks eyes\nwith an enemy, it\nwill use a mix of\n\nPSI moves such as\nHYPNOSIS and\nCONFUSION",
        "Avoid eye contact\nif you come across\none. It will try\n\nto put you to\nsleep by using\nits pendulum",
    ),
    Gen1DexEntry(
        "IVYSAUR",
        "SEED",
        3, 3, 290,
        "When the bulb on\nits back grows\nlarge, it appears\n\nto lose the\nability to stand\non its hind legs",
        "The bulb on its\nback grows by\ndrawing energy.\n\nIt gives off an\naroma when it is\nready to bloom",
    ),
    Gen1DexEntry(
        "JIGGLYPUFF",
        "BALLOON",
        1, 8, 120,
        "When its huge eyes\nlight up, it sings\na mysteriously\n\nsoothing melody\nthat lulls its\nenemies to sleep",
        "Uses its alluring\neyes to enrapture\nits foe. It then\n\nsings a pleasing\nmelody that lulls\nthe foe to sleep",
    ),
    Gen1DexEntry(
        "JOLTEON",
        "LIGHTNING",
        2, 7, 540,
        "It accumulates\nnegative ions in\nthe atmosphere to\n\nblast out 10000-\nvolt lightning\nbolts",
        "A sensitive POKé-\nMON that easily\nbecomes sad or\n\nangry. Every time\nits mood changes,\nit charges power",
    ),
    Gen1DexEntry(
        "JYNX",
        "HUMANSHAPE",
        4, 7, 900,
        "It seductively\nwiggles its hips\nas it walks. It\n\ncan cause people\nto dance in\nunison with it",
        "Appears to move\nto a rhythm of\nits own, as if it\n\nwere dancing. It\nwiggles its hips\nas it walks",
    ),
    Gen1DexEntry(
        "KABUTO",
        "SHELLFISH",
        1, 8, 250,
        "A POKéMON that\nwas resurrected\nfrom a fossil\n\nfound in what was\nonce the ocean\nfloor eons ago",
        "A POKéMON that was\nrecovered from a\nfossil. It uses\n\nthe eyes on its\nback while hiding\non the sea floor",
    ),
    Gen1DexEntry(
        "KABUTOPS",
        "SHELLFISH",
        4, 3, 890,
        "Its sleek shape is\nperfect for swim-\nming. It slashes\n\nprey with its\nclaws and drains\nthe body fluids",
        "A slim and fast\nswimmer. It slices\nits prey with its\n\nsharp sickles and\ndrinks the body\nfluids",
    ),
    Gen1DexEntry(
        "KADABRA",
        "PSI",
        4, 3, 1250,
        "It emits special\nalpha waves from\nits body that\n\ninduce headaches\njust by being\nclose by",
        "Many odd things\nhappen if this\nPOKéMON is close\n\nby. For example,\nit makes clocks\nrun backwards",
    ),
    Gen1DexEntry(
        "KAKUNA",
        "COCOON",
        2, 0, 220,
        "Almost incapable\nof moving, this\nPOKéMON can only\n\nharden its shell\nto protect itself\nfrom predators",
        "Able to move only\nslightly. When\nendangered, it\n\nmay stick out its\nstinger and poison\nits enemy",
    ),
    Gen1DexEntry(
        "KANGASKHAN",
        "PARENT",
        7, 3, 1760,
        "The infant rarely\nventures out of\nits mother's\n\nprotective pouch\nuntil it is 3\nyears old",
        "Raises its young\nin its belly\npouch. Won't run\n\nfrom any fight\nto keep its young\nprotected",
    ),
    Gen1DexEntry(
        "KINGLER",
        "PINCER",
        4, 3, 1320,
        "The large pincer\nhas 10000 hp of\ncrushing power.\n\nHowever, its huge\nsize makes it\nunwieldy to use",
        "One claw grew\nmassively and as\nhard as steel.\n\nIt has 10,000-HP\nstrength. However,\nit is too heavy",
    ),
    Gen1DexEntry(
        "KOFFING",
        "POISON GAS",
        2, 0, 20,
        "Because it stores\nseveral kinds of\ntoxic gases in\n\nits body, it is\nprone to exploding\nwithout warning",
        "In hot places, its\ninternal gases\ncould expand and\n\nexplode without\nany warning. Be\nvery careful!",
    ),
    Gen1DexEntry(
        "KRABBY",
        "RIVER CRAB",
        1, 4, 140,
        "Its pincers are\nnot only powerful\nweapons, they are\n\nused for balance\nwhen walking\nsideways",
        "Its pincers are\nsuperb weapons.\nThey sometimes\n\nbreak off during\nbattle, but they\ngrow back fast",
    ),
    Gen1DexEntry(
        "LAPRAS",
        "TRANSPORT",
        8, 2, 4850,
        "A POKéMON that\nhas been over-\nhunted almost to\n\nextinction. It\ncan ferry people\nacross the water",
        "A gentle soul that\ncan read the minds\nof people. It can\n\nferry people\nacross the sea on\nits back",
    ),
    Gen1DexEntry(
        "LICKITUNG",
        "LICKING",
        3, 11, 1440,
        "Its tongue can be\nextended like a\nchameleon's. It\n\nleaves a tingling\nsensation when it\nlicks enemies",
        "Its tongue spans\nalmost 7 feet and\nmoves more freely\n\nthan its forelegs.\nIts licks can\ncause paralysis",
    ),
    Gen1DexEntry(
        "MACHAMP",
        "SUPERPOWER",
        5, 3, 2870,
        "Using its heavy\nmuscles, it throws\npowerful punches\n\nthat can send the\nvictim clear over\nthe horizon",
        "One arm alone can\nmove mountains.\nUsing all four\n\narms, this POKéMON\nfires off awesome\npunches",
    ),
    Gen1DexEntry(
        "MACHOKE",
        "SUPERPOWER",
        4, 11, 1550,
        "Its muscular body\nis so powerful, it\nmust wear a power\n\nsave belt to be\nable to regulate\nits motions",
        "The belt around\nits waist holds\nback its energy.\n\nWithout it, this\nPOKéMON would be\nunstoppable",
    ),
    Gen1DexEntry(
        "MACHOP",
        "SUPERPOWER",
        2, 7, 430,
        "Loves to build\nits muscles.\nIt trains in all\n\nstyles of martial\narts to become\neven stronger",
        "Very powerful in\nspite of its small\nsize. Its mastery\n\nof many types of\nmartial arts makes\nit very tough",
    ),
    Gen1DexEntry(
        "MAGIKARP",
        "FISH",
        2, 11, 220,
        "In the distant\npast, it was\nsomewhat stronger\n\nthan the horribly\nweak descendants\nthat exist today",
        "Famous for being\nvery unreliable.\nIt can be found\n\nswimming in seas,\nlakes, rivers and\nshallow puddles",
    ),
    Gen1DexEntry(
        "MAGMAR",
        "SPITFIRE",
        4, 3, 980,
        "Its body always\nburns with an\norange glow that\n\nenables it to\nhide perfectly\namong flames",
        "Born in an active\nvolcano. Its body\nis always cloaked\n\nin flames, so it\nlooks like a big\nball of fire",
    ),
    Gen1DexEntry(
        "MAGNEMITE",
        "MAGNET",
        1, 0, 130,
        "Uses anti-gravity\nto stay suspended.\nAppears without\n\nwarning and uses\nTHUNDER WAVE and\nsimilar moves",
        "It is born with\nthe ability to\ndefy gravity. It\n\nfloats in air on\npowerful electro-\nmagnetic waves",
    ),
    Gen1DexEntry(
        "MAGNETON",
        "MAGNET",
        3, 3, 1320,
        "Formed by several\nMAGNEMITEs linked\ntogether. They\n\nfrequently appear\nwhen sunspots\nflare up",
        "Generates strange\nradio signals. It\nraises the tem-\n\nperature by 3.6F\ndegrees within\n3,300 feet",
    ),
    Gen1DexEntry(
        "MANKEY",
        "PIG MONKEY",
        1, 8, 620,
        "Extremely quick to\nanger. It could\nbe docile one\n\nmoment then\nthrashing away\nthe next instant",
        "An agile POKéMON\nthat lives in\ntrees. It angers\n\neasily and will\nnot hesitate to\nattack anything",
    ),
    Gen1DexEntry(
        "MAROWAK",
        "BONEKEEPER",
        3, 3, 990,
        "The bone it holds\nis its key weapon.\nIt throws the\n\nbone skillfully\nlike a boomerang\nto KO targets",
        "Small and weak,\nthis POKéMON is\nadept with its\n\nbone club. It has\ngrown more vicious\nover the ages",
    ),
    Gen1DexEntry(
        "MEOWTH",
        "SCRATCHCAT",
        1, 4, 90,
        "Adores circular\nobjects. Wanders\nthe streets on a\n\nnightly basis to\nlook for dropped\nloose change",
        "Appears to be more\nactive at night.\nIt loves round\n\nand shiny things.\nIt can't stop from\npicking them up",
    ),
    Gen1DexEntry(
        "METAPOD",
        "COCOON",
        2, 4, 220,
        "This POKéMON is\nvulnerable to\nattack while its\n\nshell is soft,\nexposing its weak\nand tender body",
        "Hardens its shell\nto protect itself.\nHowever, a large\n\nimpact may cause\nit to pop out of\nits shell",
    ),
    Gen1DexEntry(
        "MEW",
        "NEW SPECIE",
        1, 4, 90,
        "So rare that it\nis still said to\nbe a mirage by\n\nmany experts. Only\na few people have\nseen it worldwide",
        "When viewed\nthrough a micro-\nscope, this\n\nPOKéMON's short,\nfine, delicate\nhair can be seen",
    ),
    Gen1DexEntry(
        "MEWTWO",
        "GENETIC",
        6, 7, 2690,
        "It was created by\na scientist after\nyears of horrific\n\ngene splicing and\nDNA engineering\nexperiments",
        "Its DNA is almost\nthe same as MEW's.\nHowever, its size\n\nand disposition\nare vastly dif-\nferent",
    ),
    Gen1DexEntry(
        "MOLTRES",
        "FLAME",
        6, 7, 1320,
        "Known as the\nlegendary bird of\nfire. Every flap\n\nof its wings\ncreates a dazzling\nflash of flames",
        "A legendary bird\nPOKéMON. As it\nflaps its flaming\n\nwings, even the\nnight sky will\nturn red",
    ),
    Gen1DexEntry(
        "MR_MIME",
        "BARRIER",
        4, 3, 1200,
        "If interrupted\nwhile it is\nmiming, it will\n\nslap around the\noffender with its\nbroad hands",
        "Always practices\nits pantomime act.\nIt makes enemies\n\nbelieve something\nexists that\nreally doesn't",
    ),
    Gen1DexEntry(
        "MUK",
        "SLUDGE",
        3, 11, 660,
        "Thickly covered\nwith a filthy,\nvile sludge. It\n\nis so toxic, even\nits footprints\ncontain poison",
        "Smells so awful,\nit can cause\nfainting. Through\n\ndegeneration, it\nlost its sense of\nsmell",
    ),
    Gen1DexEntry(
        "NIDOKING",
        "DRILL",
        4, 7, 1370,
        "It uses its\npowerful tail in\nbattle to smash,\n\nconstrict, then\nbreak the prey's\nbones",
        "Its steel-like\nhide adds to its\npowerful tackle.\n\nIts horns are so\nhard, they can\npierce a diamond",
    ),
    Gen1DexEntry(
        "NIDOQUEEN",
        "DRILL",
        4, 3, 1320,
        "Its hard scales\nprovide strong\nprotection. It\n\nuses its hefty\nbulk to execute\npowerful moves",
        "Tough scales cover\nthe sturdy body\nof this POKéMON.\n\nIt appears that\nthe scales grow\nin cycles",
    ),
    Gen1DexEntry(
        "NIDORAN_F",
        "POISON PIN",
        1, 4, 150,
        "Although small,\nits venomous\nbarbs render this\n\nPOKéMON dangerous.\nThe female has\nsmaller horns",
        "A mild-mannered\nPOKéMON that does\nnot like to\n\nfight. Beware, its\nsmall horns\nsecrete venom",
    ),
    Gen1DexEntry(
        "NIDORAN_M",
        "POISON PIN",
        1, 8, 200,
        "Stiffens its ears\nto sense danger.\nThe larger its\n\nhorns, the more\npowerful its\nsecreted venom",
        "Its large ears\nare always kept\nupright. If it\n\nsenses danger, it\nwill attack with a\npoisonous sting",
    ),
    Gen1DexEntry(
        "NIDORINA",
        "POISON PIN",
        2, 7, 440,
        "The female's horn\ndevelops slowly.\nPrefers physical\n\nattacks such as\nclawing and\nbiting",
        "When resting deep\nin its burrow, its\nthorns always\n\nretract.\nThis is proof that\nit is relaxed",
    ),
    Gen1DexEntry(
        "NIDORINO",
        "POISON PIN",
        2, 11, 430,
        "An aggressive\nPOKéMON that is\nquick to attack.\n\nThe horn on its\nhead secretes a\npowerful venom",
        "Its horns contain\nvenom. If they\nare stabbed into\n\nan enemy, the\nimpact makes the\npoison leak out",
    ),
    Gen1DexEntry(
        "NINETALES",
        "FOX",
        3, 7, 440,
        "Very smart and\nvery vengeful.\nGrabbing one of\n\nits many tails\ncould result in a\n1000-year curse",
        "According to an\nenduring legend,\n9 noble saints\n\nwere united and\nreincarnated as\nthis POKéMON",
    ),
    Gen1DexEntry(
        "ODDISH",
        "WEED",
        1, 8, 120,
        "During the day,\nit keeps its face\nburied in the\n\nground. At night,\nit wanders around\nsowing its seeds",
        "It may be mistaken\nfor a clump of\nweeds. If you try\n\nto yank it out of\nthe ground, it\nshrieks horribly",
    ),
    Gen1DexEntry(
        "OMANYTE",
        "SPIRAL",
        1, 4, 170,
        "Although long\nextinct, in rare\ncases, it can be\n\ngenetically\nresurrected from\nfossils",
        "An ancient POKéMON\nthat was recovered\nfrom a fossil. It\n\nswims by cleverly\ntwisting its 10\ntentacles about",
    ),
    Gen1DexEntry(
        "OMASTAR",
        "SPIRAL",
        3, 3, 770,
        "A prehistoric\nPOKéMON that died\nout when its\n\nheavy shell made\nit impossible to\ncatch prey",
        "Sharp beaks ring\nits mouth. Its\nshell was too big\n\nfor it to move\nfreely, so it\nbecame extinct",
    ),
    Gen1DexEntry(
        "ONIX",
        "ROCK SNAKE",
        28, 10, 4630,
        "As it grows, the\nstone portions of\nits body harden\n\nto become similar\nto a diamond, but\ncolored black",
        "Burrows at high\nspeed in search\nof food. The\n\ntunnels it leaves\nare used as homes\nby DIGLETTs",
    ),
    Gen1DexEntry(
        "PARAS",
        "MUSHROOM",
        1, 0, 120,
        "Burrows to suck\ntree roots. The\nmushrooms on its\n\nback grow by draw-\ning nutrients from\nthe bug host",
        "Burrows under the\nground to gnaw on\ntree roots. The\n\nmushrooms on its\nback absorb most\nof the nutrition",
    ),
    Gen1DexEntry(
        "PARASECT",
        "MUSHROOM",
        3, 3, 650,
        "A host-parasite\npair in which the\nparasite mushroom\n\nhas taken over the\nhost bug. Prefers\ndamp places",
        "The bug host is\ndrained of energy\nby the mushrooms\n\non its back. They\nappear to do all\nthe thinking",
    ),
    Gen1DexEntry(
        "PERSIAN",
        "CLASSY CAT",
        3, 3, 710,
        "Although its fur\nhas many admirers,\nit is tough to\n\nraise as a pet\nbecause of its\nfickle meanness",
        "The gem in its\nforehead glows on\nits own! It walks\n\nwith all the grace\nand elegance of a\nproud queen",
    ),
    Gen1DexEntry(
        "PIDGEOT",
        "BIRD",
        4, 11, 870,
        "When hunting, it\nskims the surface\nof water at high\n\nspeed to pick off\nunwary prey such\nas MAGIKARP",
        "This POKéMON flies\nat Mach 2 speed,\nseeking prey.\n\nIts large talons\nare feared as\nwicked weapons",
    ),
    Gen1DexEntry(
        "PIDGEOTTO",
        "BIRD",
        3, 7, 660,
        "Very protective\nof its sprawling\nterritorial area,\n\nthis POKéMON will\nfiercely peck at\nany intruder",
        "This POKéMON is\nfull of vitality.\nIt constantly\n\nflies around its\nlarge territory in\nsearch of prey",
    ),
    Gen1DexEntry(
        "PIDGEY",
        "TINY BIRD",
        1, 0, 40,
        "A common sight in\nforests and woods.\nIt flaps its\n\nwings at ground\nlevel to kick up\nblinding sand",
        "Very docile. If\nattacked, it will\noften kick up\n\nsand to protect\nitself rather\nthan fight back",
    ),
    Gen1DexEntry(
        "PIKACHU",
        "MOUSE",
        1, 4, 130,
        "When several of\nthese POKéMON\ngather, their\n\nelectricity could\nbuild and cause\nlightning storms",
        "It keeps its tail\nraised to monitor\nits surroundings.\n\nIf you yank its\ntail, it will try\nto bite you",
    ),
    Gen1DexEntry(
        "PINSIR",
        "STAGBEETLE",
        4, 11, 1210,
        "If it fails to\ncrush the victim\nin its pincers,\n\nit will swing it\naround and toss\nit hard",
        "Grips its prey in\nits pincers and\nsqueezes hard! It\n\ncan't move if it's\ncold, so it lives\nin warm places",
    ),
    Gen1DexEntry(
        "POLIWAG",
        "TADPOLE",
        2, 0, 270,
        "Its newly grown\nlegs prevent it\nfrom running. It\n\nappears to prefer\nswimming than\ntrying to stand",
        "The direction of\nthe spiral on the\nbelly differs by\n\narea. It is more\nadept at swimming\nthan walking",
    ),
    Gen1DexEntry(
        "POLIWHIRL",
        "TADPOLE",
        3, 3, 440,
        "Capable of living\nin or out of\nwater. When out\n\nof water, it\nsweats to keep\nits body slimy",
        "Under attack, it\nuses its belly \nspiral to put the\n\nfoe to sleep. It\nthen makes its\nescape",
    ),
    Gen1DexEntry(
        "POLIWRATH",
        "TADPOLE",
        4, 3, 1190,
        "An adept swimmer\nat both the front\ncrawl and breast\n\nstroke. Easily\novertakes the best\nhuman swimmers",
        "Swims powerfully\nusing all the\nmuscles in its\n\nbody. It can even\novertake champion\nswimmers",
    ),
    Gen1DexEntry(
        "PONYTA",
        "FIRE HORSE",
        3, 3, 660,
        "Its hooves are 10\ntimes harder than\ndiamonds. It can\n\ntrample anything\ncompletely flat\nin little time",
        "Capable of jumping\nincredibly high.\nIts hooves and\n\nsturdy legs absorb\nthe impact of a\nhard landing",
    ),
    Gen1DexEntry(
        "PORYGON",
        "VIRTUAL",
        2, 7, 800,
        "A POKéMON that\nconsists entirely\nof programming\n\ncode. Capable of\nmoving freely in\ncyberspace",
        "The only POKéMON\npeople anticipate\ncan fly into\n\nspace. None has\nmanaged the feat\nyet, however",
    ),
    Gen1DexEntry(
        "PRIMEAPE",
        "PIG MONKEY",
        3, 3, 710,
        "Always furious\nand tenacious to\nboot. It will not\n\nabandon chasing\nits quarry until\nit is caught",
        "It stops being\nangry only when\nnobody else is\n\naround. To view\nthis moment is\nvery difficult",
    ),
    Gen1DexEntry(
        "PSYDUCK",
        "DUCK",
        2, 7, 430,
        "While lulling its\nenemies with its\nvacant look, this\n\nwily POKéMON will\nuse psychokinetic\npowers",
        "Always tormented\nby headaches.\nIt uses psychic\n\npowers, but it is\nnot known if it\nintends to do so",
    ),
    Gen1DexEntry(
        "RAICHU",
        "MOUSE",
        2, 7, 660,
        "Its long tail\nserves as a\nground to protect\n\nitself from its\nown high voltage\npower",
        "When electricity\nbuilds up inside\nits body, it\n\nbecomes feisty.\nIt also glows in\nthe dark",
    ),
    Gen1DexEntry(
        "RAPIDASH",
        "FIRE HORSE",
        5, 7, 2090,
        "Very competitive,\nthis POKéMON will\nchase anything\n\nthat moves fast\nin the hopes of\nracing it",
        "Just loves to run.\nIf it sees some-\nthing faster than\n\nitself, it will\ngive chase at top\nspeed",
    ),
    Gen1DexEntry(
        "RATICATE",
        "RAT",
        2, 4, 410,
        "It uses its whis-\nkers to maintain\nits balance.\n\nIt apparently\nslows down if\nthey are cut off",
        "Its hind feet are\nwebbed. They act\nas flippers, so\n\nit can swim in\nrivers and hunt\nfor prey",
    ),
    Gen1DexEntry(
        "RATTATA",
        "RAT",
        1, 0, 80,
        "Bites anything\nwhen it attacks.\nSmall and very\n\nquick, it is a\ncommon sight in\nmany places",
        "Will chew on any-\nthing with its\nfangs. If you see\n\none, it is certain\nthat 40 more live\nin the area",
    ),
    Gen1DexEntry(
        "RHYDON",
        "DRILL",
        6, 3, 2650,
        "Protected by an\narmor-like hide,\nit is capable of\n\nliving in molten\nlava of 3,600\ndegrees",
        "Walks on its hind\nlegs. Shows signs\nof intelligence.\n\nIts armor-like\nhide even repels\nmolten lava",
    ),
    Gen1DexEntry(
        "RHYHORN",
        "SPIKES",
        3, 3, 2540,
        "Its massive bones\nare 1000 times\nharder than human\n\nbones. It can\neasily knock a\ntrailer flying",
        "A POKéMON with a\none-track mind.\nOnce it charges, \n\nit won't stop\nrunning until it\nfalls asleep",
    ),
    Gen1DexEntry(
        "SANDSHREW",
        "MOUSE",
        2, 0, 260,
        "Burrows deep\nunderground in\narid locations\n\nfar from water.\nIt only emerges\nto hunt for food",
        "Its body is dry.\nWhen it gets cold\nat night, its\n\nhide is said to\nbecome coated with\na fine dew",
    ),
    Gen1DexEntry(
        "SANDSLASH",
        "MOUSE",
        3, 3, 650,
        "Curls up into a\nspiny ball when\nthreatened. It\n\ncan roll while\ncurled up to\nattack or escape",
        "It is skilled at\nslashing enemies\nwith its claws.\n\nIf broken, they\nstart to grow back\nin a day",
    ),
    Gen1DexEntry(
        "SCYTHER",
        "MANTIS",
        4, 11, 1230,
        "With ninja-like\nagility and speed,\nit can create the\n\nillusion that\nthere is more\nthan one",
        "Leaps out of tall\ngrass and slices\nprey with its\n\nscythes. The move-\nment looks like\nthat of a ninja",
    ),
    Gen1DexEntry(
        "SEADRA",
        "DRAGON",
        3, 11, 550,
        "Capable of swim-\nming backwards by\nrapidly flapping\n\nits wing-like\npectoral fins and\nstout tail",
        "Touching the back\nfin causes numb-\nness. It hooks\n\nits tail to coral\nto stay in place\nwhile sleeping",
    ),
    Gen1DexEntry(
        "SEAKING",
        "GOLDFISH",
        4, 3, 860,
        "In the autumn\nspawning season,\nthey can be seen\n\nswimming power-\nfully up rivers\nand creeks",
        "It is the male's\njob to make a\nnest by carving\n\nout boulders in a\nstream using the\nhorn on its head",
    ),
    Gen1DexEntry(
        "SEEL",
        "SEA LION",
        3, 7, 1980,
        "The protruding\nhorn on its head\nis very hard.\n\nIt is used for\nbashing through\nthick ice",
        "Loves freezing\ncold conditions.\nRelishes swimming\n\nin a frigid cli-\nmate of around 14F\ndegrees",
    ),
    Gen1DexEntry(
        "SHELLDER",
        "BIVALVE",
        1, 0, 90,
        "Its hard shell\nrepels any kind\nof attack.\n\nIt is vulnerable\nonly when its\nshell is open",
        "The shell can\nwithstand any\nattack. However,\n\nwhen it is open,\nthe tender body\nis exposed",
    ),
    Gen1DexEntry(
        "SLOWBRO",
        "HERMITCRAB",
        5, 3, 1730,
        "The SHELLDER that\nis latched onto\nSLOWPOKE's tail\n\nis said to feed\non the host's left\nover scraps",
        "Lives lazily by\nthe sea. If the\nSHELLDER on its\n\ntail comes off,\nit becomes a\nSLOWPOKE again",
    ),
    Gen1DexEntry(
        "SLOWPOKE",
        "DOPEY",
        3, 11, 790,
        "Incredibly slow\nand dopey. It\ntakes 5 seconds\n\nfor it to feel\npain when under\nattack",
        "Incredibly slow\nand sluggish. It\nis quite content\n\nto loll about\nwithout worrying\nabout the time",
    ),
    Gen1DexEntry(
        "SNORLAX",
        "SLEEPING",
        6, 11, 10140,
        "Very lazy. Just\neats and sleeps.\nAs its rotund\n\nbulk builds, it\nbecomes steadily\nmore slothful",
        "Will eat anything,\neven if the food\nhappens to be a\n\nlittle moldy. It\nnever gets an\nupset stomach",
    ),
    Gen1DexEntry(
        "SPEAROW",
        "TINY BIRD",
        1, 0, 40,
        "Eats bugs in\ngrassy areas. It\nhas to flap its\n\nshort wings at\nhigh speed to\nstay airborne",
        "Inept at flying\nhigh. However, it\ncan fly around\n\nvery fast to\nprotect its ter-\nritory",
    ),
    Gen1DexEntry(
        "SQUIRTLE",
        "TINYTURTLE",
        1, 8, 200,
        "After birth, its\nback swells and\nhardens into a\n\nshell. Powerfully\nsprays foam from\nits mouth",
        "Shoots water at\nprey while in the\nwater.\n\nWithdraws into\nits shell when in\ndanger",
    ),
    Gen1DexEntry(
        "STARMIE",
        "MYSTERIOUS",
        3, 7, 1760,
        "Its central core\nglows with the\nseven colors of\n\nthe rainbow. Some\npeople value the\ncore as a gem",
        "The center section\nis named the core.\nPeople think it\n\nis communicating\nwhen it glows in\n7 colors",
    ),
    Gen1DexEntry(
        "STARYU",
        "STARSHAPE",
        2, 7, 760,
        "An enigmatic\nPOKéMON that can\neffortlessly\n\nregenerate any\nappendage it\nloses in battle",
        "As long as the\ncenter section is\nunharmed, it can\n\ngrow back fully\neven if it is\nchopped to bits",
    ),
    Gen1DexEntry(
        "TANGELA",
        "VINE",
        3, 3, 770,
        "The whole body is\nswathed with wide\nvines that are\n\nsimilar to sea-\nweed. Its vines\nshake as it walks",
        "Its identity is\nobscured by masses\nof thick, blue\n\nvines. The vines\nare said to never\nstop growing",
    ),
    Gen1DexEntry(
        "TAUROS",
        "WILD BULL",
        4, 7, 1950,
        "When it targets\nan enemy, it\ncharges furiously\n\nwhile whipping its\nbody with its\nlong tails",
        "A rowdy POKéMON\nwith a lot of\nstamina. Once\n\nrunning, it won't\nstop until it hits\nsomething",
    ),
    Gen1DexEntry(
        "TENTACOOL",
        "JELLYFISH",
        2, 11, 1000,
        "Drifts in shallow\nseas. Anglers who\nhook them by\n\naccident are\noften punished by\nits stinging acid",
        "It can sometimes\nbe found all dry\nand shriveled up\n\non a beach. Toss\nit back into the\nsea to revive it",
    ),
    Gen1DexEntry(
        "TENTACRUEL",
        "JELLYFISH",
        5, 3, 1210,
        "The tentacles are\nnormally kept\nshort. On hunts,\n\nthey are extended\nto ensnare and\nimmobilize prey",
        "Its 80 tentacles\ncan stretch and\ncontract freely.\n\nThey wrap around\nprey and weaken\nit with poison",
    ),
    Gen1DexEntry(
        "VAPOREON",
        "BUBBLE JET",
        3, 3, 640,
        "Lives close to\nwater. Its long\ntail is ridged\n\nwith a fin which\nis often mistaken\nfor a mermaid's",
        "Its cell structure\nis similar to\nwater molecules.\n\nIt will melt away\nand become invis-\nible in water",
    ),
    Gen1DexEntry(
        "VENOMOTH",
        "POISONMOTH",
        4, 11, 280,
        "The dust-like\nscales covering\nits wings are\n\ncolor coded to\nindicate the kinds\nof poison it has",
        "The powdery scales\non its wings are\nhard to remove.\n\nThey also contain\npoison that leaks\nout on contact",
    ),
    Gen1DexEntry(
        "VENONAT",
        "INSECT",
        3, 3, 660,
        "Lives in the\nshadows of tall\ntrees where it\n\neats insects. It\nis attracted by\nlight at night",
        "Its large eyes act\nas radars. In a\nbright place, you\n\ncan see that they\nare clusters of\nmany tiny eyes",
    ),
    Gen1DexEntry(
        "VENUSAUR",
        "SEED",
        6, 7, 2210,
        "The plant blooms\nwhen it is\nabsorbing solar\n\nenergy. It stays\non the move to\nseek sunlight",
        "The flower on its\nback catches the\nsun's rays.\n\nThe sunlight is\nthen absorbed and\nused for energy",
    ),
    Gen1DexEntry(
        "VICTREEBEL",
        "FLYCATCHER",
        5, 7, 340,
        "Said to live in\nhuge colonies\ndeep in jungles,\n\nalthough no one\nhas ever returned\nfrom there",
        "Lures prey with\nthe sweet aroma of\nhoney. Swallowed\n\nwhole, the prey is\nmelted in a day,\nbones and all",
    ),
    Gen1DexEntry(
        "VILEPLUME",
        "FLOWER",
        3, 11, 410,
        "The larger its\npetals, the more\ntoxic pollen it\n\ncontains. Its big\nhead is heavy and\nhard to hold up",
        "Flaps its broad\nflower petals to\nscatter its\n\npoisonous pollen.\nThe flapping sound\nis very loud",
    ),
    Gen1DexEntry(
        "VOLTORB",
        "BALL",
        1, 8, 230,
        "Usually found in\npower plants.\nEasily mistaken\n\nfor a POKé BALL,\nthey have zapped\nmany people",
        "It is said to\ncamouflage itself\nas a POKé BALL. It\n\nwill self-destruct\nwith very little\nstimulus",
    ),
    Gen1DexEntry(
        "VULPIX",
        "FOX",
        2, 0, 220,
        "At the time of\nbirth, it has\njust one tail.\n\nThe tail splits\nfrom its tip as\nit grows older",
        "Both its fur and\nits tails are\nbeautiful. As it\n\ngrows, the tails\nsplit and form\nmore tails",
    ),
    Gen1DexEntry(
        "WARTORTLE",
        "TURTLE",
        3, 3, 500,
        "Often hides in\nwater to stalk\nunwary prey. For\n\nswimming fast, it\nmoves its ears to\nmaintain balance",
        "When tapped, this\nPOKéMON will pull\nin its head, but\n\nits tail will\nstill stick out a\nlittle bit",
    ),
    Gen1DexEntry(
        "WEEDLE",
        "HAIRY BUG",
        1, 0, 70,
        "Often found in\nforests, eating\nleaves.\n\nIt has a sharp\nvenomous stinger\non its head",
        "Beware of the\nsharp stinger on\nits head. It\n\nhides in grass\nand bushes where\nit eats leaves",
    ),
    Gen1DexEntry(
        "WEEPINBELL",
        "FLYCATCHER",
        3, 3, 140,
        "It spits out\nPOISONPOWDER to\nimmobilize the\n\nenemy and then\nfinishes it with\na spray of ACID",
        "When hungry, it\nswallows anything\nthat moves. Its\n\nhapless prey is\nmelted inside by\nstrong acids",
    ),
    Gen1DexEntry(
        "WEEZING",
        "POISON GAS",
        3, 11, 210,
        "Where two kinds\nof poison gases\nmeet, 2 KOFFINGs\n\ncan fuse into a\nWEEZING over many\nyears",
        "It lives and grows\nby absorbing dust,\ngerms and poison\n\ngases that are\ncontained in toxic\nwaste and garbage",
    ),
    Gen1DexEntry(
        "WIGGLYTUFF",
        "BALLOON",
        3, 3, 260,
        "The body is soft\nand rubbery. When\nangered, it will\n\nsuck in air and\ninflate itself to\nan enormous size",
        "Its body is full\nof elasticity. By\ninhaling deeply,\n\nit can continue\nto inflate itself\nwithout limit",
    ),
    Gen1DexEntry(
        "ZAPDOS",
        "ELECTRIC",
        5, 3, 1160,
        "A legendary bird\nPOKéMON that is\nsaid to appear\n\nfrom clouds while\ndropping enormous\nlightning bolts",
        "This legendary\nbird POKéMON is\nsaid to appear\n\nwhen the sky turns\ndark and lightning\nshowers down",
    ),
    Gen1DexEntry(
        "ZUBAT",
        "BAT",
        2, 7, 170,
        "Forms colonies in\nperpetually dark\nplaces. Uses\n\nultrasonic waves\nto identify and\napproach targets",
        "Emits ultrasonic\ncries while it\nflies. They act\n\nas a sonar used\nto check for ob-\njects in its way",
    ),
)
