// GENERATED FILE - do not edit by hand.
// Source: pret/pokecrystal @ 7a7881d0d62e0ddbd82dcf10e7116807487ac651, via tools/generate_gen2_items.py.
package com.logie.gen1storage.pokemon

/** Every item by its index, which is what a held-item byte holds. */
internal val GEN2_ITEM_ORDER: List<String?> = listOf(
    "NO_ITEM", // 00
    "MASTER_BALL", // 01
    "ULTRA_BALL", // 02
    "BRIGHTPOWDER", // 03
    "GREAT_BALL", // 04
    "POKE_BALL", // 05
    "TOWN_MAP", // 06
    "BICYCLE", // 07
    "MOON_STONE", // 08
    "ANTIDOTE", // 09
    "BURN_HEAL", // 0a
    "ICE_HEAL", // 0b
    "AWAKENING", // 0c
    "PARLYZ_HEAL", // 0d
    "FULL_RESTORE", // 0e
    "MAX_POTION", // 0f
    "HYPER_POTION", // 10
    "SUPER_POTION", // 11
    "POTION", // 12
    "ESCAPE_ROPE", // 13
    "REPEL", // 14
    "MAX_ELIXER", // 15
    "FIRE_STONE", // 16
    "THUNDERSTONE", // 17
    "WATER_STONE", // 18
    "ITEM_19", // 19
    "HP_UP", // 1a
    "PROTEIN", // 1b
    "IRON", // 1c
    "CARBOS", // 1d
    "LUCKY_PUNCH", // 1e
    "CALCIUM", // 1f
    "RARE_CANDY", // 20
    "X_ACCURACY", // 21
    "LEAF_STONE", // 22
    "METAL_POWDER", // 23
    "NUGGET", // 24
    "POKE_DOLL", // 25
    "FULL_HEAL", // 26
    "REVIVE", // 27
    "MAX_REVIVE", // 28
    "GUARD_SPEC", // 29
    "SUPER_REPEL", // 2a
    "MAX_REPEL", // 2b
    "DIRE_HIT", // 2c
    "ITEM_2D", // 2d
    "FRESH_WATER", // 2e
    "SODA_POP", // 2f
    "LEMONADE", // 30
    "X_ATTACK", // 31
    "ITEM_32", // 32
    "X_DEFEND", // 33
    "X_SPEED", // 34
    "X_SPECIAL", // 35
    "COIN_CASE", // 36
    "ITEMFINDER", // 37
    "POKE_FLUTE", // 38
    "EXP_SHARE", // 39
    "OLD_ROD", // 3a
    "GOOD_ROD", // 3b
    "SILVER_LEAF", // 3c
    "SUPER_ROD", // 3d
    "PP_UP", // 3e
    "ETHER", // 3f
    "MAX_ETHER", // 40
    "ELIXER", // 41
    "RED_SCALE", // 42
    "SECRETPOTION", // 43
    "S_S_TICKET", // 44
    "MYSTERY_EGG", // 45
    "CLEAR_BELL", // 46
    "SILVER_WING", // 47
    "MOOMOO_MILK", // 48
    "QUICK_CLAW", // 49
    "PSNCUREBERRY", // 4a
    "GOLD_LEAF", // 4b
    "SOFT_SAND", // 4c
    "SHARP_BEAK", // 4d
    "PRZCUREBERRY", // 4e
    "BURNT_BERRY", // 4f
    "ICE_BERRY", // 50
    "POISON_BARB", // 51
    "KINGS_ROCK", // 52
    "BITTER_BERRY", // 53
    "MINT_BERRY", // 54
    "RED_APRICORN", // 55
    "TINYMUSHROOM", // 56
    "BIG_MUSHROOM", // 57
    "SILVERPOWDER", // 58
    "BLU_APRICORN", // 59
    "ITEM_5A", // 5a
    "AMULET_COIN", // 5b
    "YLW_APRICORN", // 5c
    "GRN_APRICORN", // 5d
    "CLEANSE_TAG", // 5e
    "MYSTIC_WATER", // 5f
    "TWISTEDSPOON", // 60
    "WHT_APRICORN", // 61
    "BLACKBELT_I", // 62
    "BLK_APRICORN", // 63
    "ITEM_64", // 64
    "PNK_APRICORN", // 65
    "BLACKGLASSES", // 66
    "SLOWPOKETAIL", // 67
    "PINK_BOW", // 68
    "STICK", // 69
    "SMOKE_BALL", // 6a
    "NEVERMELTICE", // 6b
    "MAGNET", // 6c
    "MIRACLEBERRY", // 6d
    "PEARL", // 6e
    "BIG_PEARL", // 6f
    "EVERSTONE", // 70
    "SPELL_TAG", // 71
    "RAGECANDYBAR", // 72
    "GS_BALL", // 73
    "BLUE_CARD", // 74
    "MIRACLE_SEED", // 75
    "THICK_CLUB", // 76
    "FOCUS_BAND", // 77
    "ITEM_78", // 78
    "ENERGYPOWDER", // 79
    "ENERGY_ROOT", // 7a
    "HEAL_POWDER", // 7b
    "REVIVAL_HERB", // 7c
    "HARD_STONE", // 7d
    "LUCKY_EGG", // 7e
    "CARD_KEY", // 7f
    "MACHINE_PART", // 80
    "EGG_TICKET", // 81
    "LOST_ITEM", // 82
    "STARDUST", // 83
    "STAR_PIECE", // 84
    "BASEMENT_KEY", // 85
    "PASS", // 86
    "ITEM_87", // 87
    "ITEM_88", // 88
    "ITEM_89", // 89
    "CHARCOAL", // 8a
    "BERRY_JUICE", // 8b
    "SCOPE_LENS", // 8c
    "ITEM_8D", // 8d
    "ITEM_8E", // 8e
    "METAL_COAT", // 8f
    "DRAGON_FANG", // 90
    "ITEM_91", // 91
    "LEFTOVERS", // 92
    "ITEM_93", // 93
    "ITEM_94", // 94
    "ITEM_95", // 95
    "MYSTERYBERRY", // 96
    "DRAGON_SCALE", // 97
    "BERSERK_GENE", // 98
    "ITEM_99", // 99
    "ITEM_9A", // 9a
    "ITEM_9B", // 9b
    "SACRED_ASH", // 9c
    "HEAVY_BALL", // 9d
    "FLOWER_MAIL", // 9e
    "LEVEL_BALL", // 9f
    "LURE_BALL", // a0
    "FAST_BALL", // a1
    "ITEM_A2", // a2
    "LIGHT_BALL", // a3
    "FRIEND_BALL", // a4
    "MOON_BALL", // a5
    "LOVE_BALL", // a6
    "NORMAL_BOX", // a7
    "GORGEOUS_BOX", // a8
    "SUN_STONE", // a9
    "POLKADOT_BOW", // aa
    "ITEM_AB", // ab
    "UP_GRADE", // ac
    "BERRY", // ad
    "GOLD_BERRY", // ae
    "SQUIRTBOTTLE", // af
    "ITEM_B0", // b0
    "PARK_BALL", // b1
    "RAINBOW_WING", // b2
    "ITEM_B3", // b3
    "BRICK_PIECE", // b4
    "SURF_MAIL", // b5
    "LITEBLUEMAIL", // b6
    "PORTRAITMAIL", // b7
    "LOVELY_MAIL", // b8
    "EON_MAIL", // b9
    "MORPH_MAIL", // ba
    "BLUESKY_MAIL", // bb
    "MUSIC_MAIL", // bc
    "MIRAGE_MAIL", // bd
    "ITEM_BE", // be
    "TM_", // bf
    "TM_DYNAMICPUNCH", // c0
    "TM_HEADBUTT", // c1
    "TM_CURSE", // c2
    "TM_ROLLOUT", // c3
    "ITEM_C3", // c4
    "TM_ROAR", // c5
    "TM_TOXIC", // c6
    "TM_ZAP_CANNON", // c7
    "TM_ROCK_SMASH", // c8
    "TM_PSYCH_UP", // c9
    "TM_HIDDEN_POWER", // ca
    "TM_SUNNY_DAY", // cb
    "TM_SWEET_SCENT", // cc
    "TM_SNORE", // cd
    "TM_BLIZZARD", // ce
    "TM_HYPER_BEAM", // cf
    "TM_ICY_WIND", // d0
    "TM_PROTECT", // d1
    "TM_RAIN_DANCE", // d2
    "TM_GIGA_DRAIN", // d3
    "TM_ENDURE", // d4
    "TM_FRUSTRATION", // d5
    "TM_SOLARBEAM", // d6
    "TM_IRON_TAIL", // d7
    "TM_DRAGONBREATH", // d8
    "TM_THUNDER", // d9
    "TM_EARTHQUAKE", // da
    "TM_RETURN", // db
    "TM_DIG", // dc
    "ITEM_DC", // dd
    "TM_PSYCHIC_M", // de
    "TM_SHADOW_BALL", // df
    "TM_MUD_SLAP", // e0
    "TM_DOUBLE_TEAM", // e1
    "TM_ICE_PUNCH", // e2
    "TM_SWAGGER", // e3
    "TM_SLEEP_TALK", // e4
    "TM_SLUDGE_BOMB", // e5
    "TM_SANDSTORM", // e6
    "TM_FIRE_BLAST", // e7
    "TM_SWIFT", // e8
    "TM_DEFENSE_CURL", // e9
    "TM_THUNDERPUNCH", // ea
    "TM_DREAM_EATER", // eb
    "TM_DETECT", // ec
    "TM_REST", // ed
    "TM_ATTRACT", // ee
    "TM_THIEF", // ef
    "TM_STEEL_WING", // f0
    "TM_FIRE_PUNCH", // f1
    "TM_FURY_CUTTER", // f2
    "TM_NIGHTMARE", // f3
    "HM_", // f4
    "HM_CUT", // f5
    "HM_FLY", // f6
    "HM_SURF", // f7
    "HM_STRENGTH", // f8
    "HM_FLASH", // f9
    "HM_WHIRLPOOL", // fa
    "HM_WATERFALL", // fb
    "ITEM_FA", // fc
)

/**
 * The catch rates Generation II rewrites rather than reading as an item
 * index, from data/items/catch_rate_items.asm.
 */
internal val GEN2_CATCH_RATE_ITEMS: Map<Int, String> = mapOf(
    25 to "LEFTOVERS",
    45 to "BITTER_BERRY",
    50 to "GOLD_BERRY",
    90 to "BERRY",
    100 to "BERRY",
    120 to "BERRY",
    135 to "BERRY",
    190 to "BERRY",
    196 to "BERRY",
    221 to "BERRY",
    252 to "BERRY",
    255 to "BERRY",
)
